### PR TITLE
Detect command path when launching

### PR DESCRIPTION
**Pull request by kaneshin**
Hi.

I've enhanced what detecting command path when app launching automatically if exists.

Thanks,

### CODE REVIEW

**Comment by kaneshin** [comment]
https://www.dropbox.com/s/f7uocp1yuaer4g0/livediag.mov?dl=0

**Comment by kaneshin** [comment]
Oops, I found bugs.. Please wait several minutes.

**Comment by kaneshin** [comment]
Fix it.

- Set path by command `which` if text box is blank and exists the command.

**Comment by dataich** [comment]
I'm really sorry for late response :bow:
And thank you for great PR.

**Pull request merged**
